qseecom: Fix -Wstrict-prototypes
techpack/securemsm/qseecom/qseecom.c:9585:44: error: a function
declaration without a prototype is deprecated in all versions
of C [-Werror,-Wstrict-prototypes]
static int qseecom_register_reboot_notifier()
                                           ^
                                            void
1 error generated.

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>